// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment/wallet_service.proto

// Protobuf Java Version: 3.25.2
package com.example.java_projects.proto;

public interface CreateWalletResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.java_projects.proto.CreateWalletResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string wallet_id = 1;</code>
   * @return The walletId.
   */
  java.lang.String getWalletId();
  /**
   * <code>string wallet_id = 1;</code>
   * @return The bytes for walletId.
   */
  com.google.protobuf.ByteString
      getWalletIdBytes();

  /**
   * <code>string owner_id = 2;</code>
   * @return The ownerId.
   */
  java.lang.String getOwnerId();
  /**
   * <code>string owner_id = 2;</code>
   * @return The bytes for ownerId.
   */
  com.google.protobuf.ByteString
      getOwnerIdBytes();

  /**
   * <code>string owner_type = 3;</code>
   * @return The ownerType.
   */
  java.lang.String getOwnerType();
  /**
   * <code>string owner_type = 3;</code>
   * @return The bytes for ownerType.
   */
  com.google.protobuf.ByteString
      getOwnerTypeBytes();

  /**
   * <code>string currency = 4;</code>
   * @return The currency.
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 4;</code>
   * @return The bytes for currency.
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>int64 balance = 5;</code>
   * @return The balance.
   */
  long getBalance();

  /**
   * <code>string created_at = 6;</code>
   * @return The createdAt.
   */
  java.lang.String getCreatedAt();
  /**
   * <code>string created_at = 6;</code>
   * @return The bytes for createdAt.
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();
}
