// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/product_service.proto

// Protobuf Java Version: 3.25.2
package com.example.java_projects.proto;

public interface GetProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.java_projects.proto.GetProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_id = 1;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 1;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>double price = 4;</code>
   * @return The price.
   */
  double getPrice();
}
