// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/product_service.proto

// Protobuf Java Version: 3.25.2
package com.example.java_projects.proto;

public interface GetProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.java_projects.proto.GetProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 product_id = 1;</code>
   * @return The productId.
   */
  long getProductId();
}
