// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/product_service.proto

// Protobuf Java Version: 3.25.2
package com.example.java_projects.proto;

public interface ListProductsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.java_projects.proto.ListProductsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.java_projects.proto.GetProductResponse products = 1;</code>
   */
  java.util.List<com.example.java_projects.proto.GetProductResponse> 
      getProductsList();
  /**
   * <code>repeated .com.example.java_projects.proto.GetProductResponse products = 1;</code>
   */
  com.example.java_projects.proto.GetProductResponse getProducts(int index);
  /**
   * <code>repeated .com.example.java_projects.proto.GetProductResponse products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .com.example.java_projects.proto.GetProductResponse products = 1;</code>
   */
  java.util.List<? extends com.example.java_projects.proto.GetProductResponseOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .com.example.java_projects.proto.GetProductResponse products = 1;</code>
   */
  com.example.java_projects.proto.GetProductResponseOrBuilder getProductsOrBuilder(
      int index);

  /**
   * <code>int32 total_count = 2;</code>
   * @return The totalCount.
   */
  int getTotalCount();
}
