// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/product_service.proto

// Protobuf Java Version: 3.25.2
package com.example.java_projects.proto;

public final class ProductServiceOuterClass {
  private ProductServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_java_projects_proto_GetProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_java_projects_proto_GetProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_java_projects_proto_GetProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_java_projects_proto_GetProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_java_projects_proto_ListProductsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_java_projects_proto_ListProductsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_java_projects_proto_ListProductsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_java_projects_proto_ListProductsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035product/product_service.proto\022\037com.exa" +
      "mple.java_projects.proto\"\'\n\021GetProductRe" +
      "quest\022\022\n\nproduct_id\030\001 \001(\t\"Z\n\022GetProductR" +
      "esponse\022\022\n\nproduct_id\030\001 \001(\t\022\014\n\004name\030\002 \001(" +
      "\t\022\023\n\013description\030\003 \001(\t\022\r\n\005price\030\004 \001(\001\"6\n" +
      "\023ListProductsRequest\022\014\n\004page\030\001 \001(\005\022\021\n\tpa" +
      "ge_size\030\002 \001(\005\"r\n\024ListProductsResponse\022E\n" +
      "\010products\030\001 \003(\01323.com.example.java_proje" +
      "cts.proto.GetProductResponse\022\023\n\013total_co" +
      "unt\030\002 \001(\0052\204\002\n\016ProductService\022u\n\nGetProdu" +
      "ct\0222.com.example.java_projects.proto.Get" +
      "ProductRequest\0323.com.example.java_projec" +
      "ts.proto.GetProductResponse\022{\n\014ListProdu" +
      "cts\0224.com.example.java_projects.proto.Li" +
      "stProductsRequest\0325.com.example.java_pro" +
      "jects.proto.ListProductsResponseB!P\001Z\035ga" +
      "teway/proto/product;productb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_java_projects_proto_GetProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_java_projects_proto_GetProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_java_projects_proto_GetProductRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_com_example_java_projects_proto_GetProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_java_projects_proto_GetProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_java_projects_proto_GetProductResponse_descriptor,
        new java.lang.String[] { "ProductId", "Name", "Description", "Price", });
    internal_static_com_example_java_projects_proto_ListProductsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_java_projects_proto_ListProductsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_java_projects_proto_ListProductsRequest_descriptor,
        new java.lang.String[] { "Page", "PageSize", });
    internal_static_com_example_java_projects_proto_ListProductsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_java_projects_proto_ListProductsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_java_projects_proto_ListProductsResponse_descriptor,
        new java.lang.String[] { "Products", "TotalCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
