// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment/wallet_service.proto

// Protobuf Java Version: 3.25.2
package com.example.java_projects.proto;

public final class WalletServiceOuterClass {
  private WalletServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_java_projects_proto_CreateWalletRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_java_projects_proto_CreateWalletRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_java_projects_proto_CreateWalletResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_java_projects_proto_CreateWalletResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034payment/wallet_service.proto\022\037com.exam" +
      "ple.java_projects.proto\"M\n\023CreateWalletR" +
      "equest\022\020\n\010owner_id\030\001 \001(\t\022\022\n\nowner_type\030\002" +
      " \001(\t\022\020\n\010currency\030\003 \001(\t\"\206\001\n\024CreateWalletR" +
      "esponse\022\021\n\twallet_id\030\001 \001(\t\022\020\n\010owner_id\030\002" +
      " \001(\t\022\022\n\nowner_type\030\003 \001(\t\022\020\n\010currency\030\004 \001" +
      "(\t\022\017\n\007balance\030\005 \001(\003\022\022\n\ncreated_at\030\006 \001(\t2" +
      "\214\001\n\rWalletService\022{\n\014CreateWallet\0224.com." +
      "example.java_projects.proto.CreateWallet" +
      "Request\0325.com.example.java_projects.prot" +
      "o.CreateWalletResponseB\037P\001Z\033gateway/prot" +
      "o/wallet;walletb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_java_projects_proto_CreateWalletRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_java_projects_proto_CreateWalletRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_java_projects_proto_CreateWalletRequest_descriptor,
        new java.lang.String[] { "OwnerId", "OwnerType", "Currency", });
    internal_static_com_example_java_projects_proto_CreateWalletResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_java_projects_proto_CreateWalletResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_java_projects_proto_CreateWalletResponse_descriptor,
        new java.lang.String[] { "WalletId", "OwnerId", "OwnerType", "Currency", "Balance", "CreatedAt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
